# GET http://localhost:5000/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsIm5hbWUiOiJSYW5nZ2EiLCJlbWFpbCI6ImR3aXJhbmdnYW9rdGF6QGdtYWlsLmNvbSIsImlhdCI6MTcxNzM4NzM2MSwiZXhwIjoxNzE3Mzg3Mzc2fQ.ksM2niuJtAzc0Nbjkpqj46g8Gdgh-OZacOOgZdeIdz4

###
POST http://localhost:5000/createUser
Content-Type: application/json

{
    "name": "Rangga",
    "email": "dwiranggaoktaz@gmail.com",
    "password": "Rangga123",
    "confirmPassword": "Rangga123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "dwiranggaoktaz@gmail.com",
    "password": "Rangga123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
